# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.img_label = QtWidgets.QLabel(self.centralwidget)
        self.img_label.setGeometry(QtCore.QRect(0, 0, 1280, 720))
        self.img_label.setText("")
        self.img_label.setObjectName("img_label")
        self.framerate_label = QtWidgets.QLabel(self.centralwidget)
        self.framerate_label.setGeometry(QtCore.QRect(1300, 40, 500, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.framerate_label.setFont(font)
        self.framerate_label.setObjectName("framerate_label")
        self.start_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.start_pushButton.setGeometry(QtCore.QRect(50, 800, 200, 100))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.start_pushButton.setFont(font)
        self.start_pushButton.setText("")
        self.start_pushButton.setObjectName("start_pushButton")
        self.right_arm_ext_count_label = QtWidgets.QLabel(self.centralwidget)
        self.right_arm_ext_count_label.setGeometry(QtCore.QRect(1300, 160, 500, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.right_arm_ext_count_label.setFont(font)
        self.right_arm_ext_count_label.setObjectName("right_arm_ext_count_label")
        self.sit_to_stand_count_label = QtWidgets.QLabel(self.centralwidget)
        self.sit_to_stand_count_label.setGeometry(QtCore.QRect(1300, 120, 500, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sit_to_stand_count_label.setFont(font)
        self.sit_to_stand_count_label.setObjectName("sit_to_stand_count_label")
        self.left_arm_ext_count_label = QtWidgets.QLabel(self.centralwidget)
        self.left_arm_ext_count_label.setGeometry(QtCore.QRect(1300, 200, 500, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.left_arm_ext_count_label.setFont(font)
        self.left_arm_ext_count_label.setObjectName("left_arm_ext_count_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.framerate_label.setText(_translate("MainWindow", "Frame Rate: "))
        self.right_arm_ext_count_label.setText(_translate("MainWindow", "Right Arm Extensions:"))
        self.sit_to_stand_count_label.setText(_translate("MainWindow", "Sit to Stand:"))
        self.left_arm_ext_count_label.setText(_translate("MainWindow", "<html><head/><body><p>Left Arm Extensions:</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
